version: '3'

services:
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    container_name: customer-api-nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./projects/:/var/www/html/
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8
      - mysql
      - phpmyadmin
    networks:
      default:
        aliases:
          - api.customer-project.test
          - customer-project.test

  php8:
    build:
      context: ./config/php8
    hostname: php8
    container_name: customer-api-php8
    ports:
      - "9000:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./config/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./config/php8/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: customer-api-mysql
    ports:
      - "3308:3306"
    depends_on:
      - php8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: customer-api-phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: mysql